const dotenv=require('dotenv').config()

PORT=process.env.PORT;
CONNECTION_STRING=process.env.CONNECTION_STRING;
ACCESS_TOKEN_SECRET=process.env.ACCESS_TOKEN_SECRET;
REFRESH_TOKEN_SECRET=process.env.REFRESH_TOKEN_SECRET;
BACLEND_SERVER_PATH=process.env.BACLEND_SERVER_PATH;
module.exports={
    PORT,CONNECTION_STRING,ACCESS_TOKEN_SECRET,REFRESH_TOKEN_SECRET,BACLEND_SERVER_PATH
}